services:
  metabolomicsusi-web:
    networks:
      - default
      - nginx-net
    environment:
      VIRTUAL_HOST: ${HOSTNAME:-metabolomics-usi.gnps2.org}
      VIRTUAL_PORT: 5000
      LETSENCRYPT_HOST: ${HOSTNAME:-metabolomics-usi.gnps2.org}
      LETSENCRYPT_EMAIL: mwang87@gmail.com
    command: /app/run_server.sh
    deploy:
      resources:
        limits:
          memory: 16000M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  metabolomicsusi-api1:
    networks:
      - default
      - nginx-net
    environment:
      VIRTUAL_HOST: ${HOSTNAME:-api.metabolomics-usi.gnps2.org}
      VIRTUAL_PORT: 5000
      LETSENCRYPT_HOST: ${HOSTNAME:-api.metabolomics-usi.gnps2.org}
      LETSENCRYPT_EMAIL: mwang87@gmail.com
    command: /app/run_server.sh
    deploy:
      resources:
        limits:
          memory: 16000M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  metabolomicsusi-worker:
    deploy:
      resources:
        limits:
          memory: 16000M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  metabolomicsusi-redis:
    deploy:
      resources:
        limits:
          memory: 8000M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  metabolomicsusi-logrotate:
    build:
      context: .
      dockerfile: Dockerfile.logrotate
    container_name: metabolomicsusi-logrotate
    volumes:
      - ./logs:/var/log/metabolomicsusi/web:rw
      - ./logsapi:/var/log/metabolomicsusi/api:rw
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  nginx-net:
    name: nginx-net
    external: true
