version: '3'
services:
  metabolomicsusi-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: metabolomicsusi-web
    ports:
    - "5087:5000"
    volumes:
        - ./tmp:/app/tmp:rw
        - ./logs/:/app/logs:rw
    networks:
      - default
    restart: on-failure
    command: /app/run_dev_server.sh

  metabolomicsusi-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: metabolomicsusi-worker
    volumes:
      - ./tmp:/app/tmp:rw
      - ./logs:/app/logs:rw
    command: /app/run_worker.sh
    restart: on-failure
    depends_on:
      - metabolomicsusi-redis
    networks:
      - default
      - nginx-net

  metabolomicsusi-redis:
    container_name: metabolomicsusi-redis
    image: redis
    networks:
      - default
    restart: on-failure

networks:
  nginx-net:
    external:
      name: nginx-net

